SIMBION_Basdat_12/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
import fitur1.urls as fitur1
import fitur2.urls as fitur2
import fitur3.urls as fitur3
import fitur5.urls as fitur5
import fitur6.urls as fitur6
import fitur4.urls as fitur4

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include((fitur1, 'fitur1'), namespace='fitur1')),
    url(r'^register/', include((fitur2, 'fitur2'), namespace='fitur2')),
    url(r'^beasiswa-baru/', include((fitur3, 'fitur3'), namespace='fitur3')),
    url(r'^', include((fitur4, 'fitur4'), namespace='fitur4')),
    url(r'^mendaftar-beasiswa/', include((fitur5, 'fitur5'), namespace='fitur5')),
    url(r'^list-beasiswa/', include((fitur6, 'fitur6'), namespace='fitur6'))
]

fitur1/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout')
]

fitur2/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^$', index, name='index')
]

templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<div style="text-align: justify; position: static; margin-bottom: 0px;">
	<p>Made with Love by Aji, Wigo, Bima</p>
</div>

templates/partials/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a style="color: white;" class="navbar-brand" href="/"><b>SIMBION</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="dropdown">
        <a class="dropdown-toggle btn btn-primary" data-toggle="dropdown" href="#">Fitur<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'fitur3:index' %}">Tambah Beassiwa</a></li>
          <li><a class="dropdown-item" href="{% url 'fitur4:index' %}">Daftar Beaiswa</a></li>
          <li><a class="dropdown-item" href="{% url 'fitur5:index' %}">Mendaftar Beasiswa</a></li>
          <li><a class="dropdown-item" href="{% url 'fitur6:index' %}">Daftar Pendaftar Beaiswa</a></li>
        </ul>
      </li>
    </ul>
    
    <ul class="navbar-nav ml-auto">
      {% if request.session.login_user is None %}
        <li class="nav-item"><a href="/login" class="btn btn-success mr-sm-2">Login</a></li>
        <li class="nav-item"><a href="/register" class="btn btn-success mr-sm-2">Register</a></li>
      {% else %}
        <li class="dropdown">
          <a class="dropdown-toggle btn btn-outline-success" data-toggle="dropdown" href="#">Welcome {{ request.session.login_user }}<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/logout" class="dropdown-item">Logout</a></li>
          </ul>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>