SIMBION_Basdat_12/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
import fitur1.urls as fitur1
import fitur2.urls as fitur2
import fitur3.urls as fitur3
import fitur5.urls as fitur5
import fitur6.urls as fitur6
import fitur4.urls as fitur4

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include((fitur1, 'fitur1'), namespace='fitur1')),
    url(r'^register/', include((fitur2, 'fitur2'), namespace='fitur2')),
    url(r'^beasiswa-baru/', include((fitur3, 'fitur3'), namespace='fitur3')),
    url(r'^', include((fitur4, 'fitur4'), namespace='fitur4')),
    url(r'^mendaftar-beasiswa/', include((fitur5, 'fitur5'), namespace='fitur5')),
    url(r'^list-beasiswa/', include((fitur6, 'fitur6'), namespace='fitur6'))
]

fitur1/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout')
]

fitur3/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^Membuat-Paket-Beasiswa-Baru', Membuat_Paket_Beasiswa_Baru, name='Membuat_Paket_Beasiswa_Baru'),
    url(r'^Menambahkan_beasiswa_dari_paket', Menambahkan_beasiswa_dari_paket, name='Menambahkan_beasiswa_dari_paket'),
    url(r'^submit_paket_beasiswa_baru', submit_paket_beasiswa_baru, name='submit_paket_beasiswa_baru'),
    url(r'^tambah_beasiswa', tambah_beasiswa, name='tambah_beasiswa'),
]

fitur3/models.py
from django.db import models

# Create your models here.

fitur3/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponse, HttpResponseRedirect



# Create your views here.
response = {}
CSRF_COOKIE_SECURE = True

def index(request):
	response['login'] = True
	html = 'daftarkan_beasiswa.html'
	return render(request, html, response)

def Membuat_Paket_Beasiswa_Baru(request):
	response['login'] = True
	html = 'Membuat_Paket_Beasiswa_Baru.html'
	return render(request, html, response)

def Menambahkan_beasiswa_dari_paket(request):
	response['login'] = True
	html = 'Menambahkan_beasiswa_dari_paket.html'
	return render(request, html, response)


def submit_paket_beasiswa_baru(request):
	print("ku mau lulus")	
	return HttpResponseRedirect('/beasiswa-baru/')

def tambah_beasiswa(request):
	print("semua mau lulus")
	return HttpResponseRedirect('/beasiswa-baru/')

fitur3/templates/Membuat_Paket_Beasiswa_Baru.html
{% extends "layout/base.html" %}
{% block content %}

  <div class="py-5"></div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-4">FORM PENDAFTARAN PAKET BEASISWA</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="" id="form" method="POST" action="{% url 'fitur3:submit_paket_beasiswa_baru' %}">
          {% csrf_token %}
            <div class="form-group">
              <label>Kode</label>
              <input  class="form-control" placeholder="Kode Beasiswa">
              <small class="form-text text-muted"></small>
            </div>
            <div class="form-group">
              <label>Nama Paket Beasiswa</label>
              <input  class="form-control" placeholder="Nama Paket Beasiswa"> </div>
            <div class="form-group">
              <small class="text-muted form-text"></small>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Jenis Paket Beasiswa</label>
              <select class="custom-control custom-select">
                <option selected="">Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
              </select>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Deskripsi</label>
              <input type="text" class="form-control" id="inlineFormInput" placeholder="Deskripsi">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Syarat Beasiswa</label>
              <input type="text" class="form-control" id="inlineFormInput" placeholder="Syarat Beasiswa">
            </div>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-primary" value="Submit">
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

fitur3/templates/Menambahkan_beasiswa_dari_paket.html
{% extends "layout/base.html" %}
{% block content %}

  <div class="py-5"></div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-4 text-left">FORM PENDAFTARAN TAMBAH BEASISWA DARI PAKET</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="" id="form" method="POST" action="{% url 'fitur3:tambah_beasiswa' %}">
          {% csrf_token %}
            <div class="form-group">
              <small class="form-text text-muted"></small>
            </div>
            <div class="form-group">
              <small class="text-muted form-text"></small>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kode Beasiswa</label>
              <select class="custom-control custom-select">
                <option selected="">Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
              </select>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Nomor Urut</label>
              <input type="text" class="form-control" id="inlineFormInput" placeholder="Nomor Urut"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Tanggal Mulai Pendaftaran</label>
              <input type="date" class="form-control" id="inlineFormInput" placeholder="Jane Doe">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Tanggal Tutup Pendaftaran</label>
              <input type="date" class="form-control" id="inlineFormInput" placeholder="Jane Doe">
            </div>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-primary" value="Submit">
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

fitur3/templates/daftarkan_beasiswa.html
{% extends "layout/base.html" %}
{% block content %}


  <div class="py-5"></div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1">Membuat Beasiswa Baru</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 px-4">
          <a class="btn btn-primary px-5" href="{% url 'fitur3:Membuat_Paket_Beasiswa_Baru' %}">Membuat Paket Beasiswa Baru</a>
        </div>
        <div class="px-5">
          <a class="btn btn-primary px-5" href="{% url 'fitur3:Menambahkan_beasiswa_dari_paket' %}">Menambahkan Beasiswa dari Paket</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}